from cv2 import FONT_HERSHEY_SIMPLEX

### GUI CONSTANTS
WINDOW_TITLE: str = "Thermal Camera"
FULLSCREEN: bool = False
HUD_VISIBLE: bool = False
LAST_SNAPSHOT_TIME: str = ""
RECORDING_START_TIME: str = ""
RECORDING_DURATION: str = "00:00:00"
FONT: int = FONT_HERSHEY_SIMPLEX
# Scale
SCALE: int = 1
SCALE_MAX: int = 5
SCALE_MIN: int = 1
SCALE_INCREMENT: int = 1

from camera.ColormapEnum import Colormap

### IMAGE PROCESSING CONSTANTS
COLORMAP: Colormap = Colormap.NONE
# Contrast
CONTRAST: float = 1.0
CONTRAST_MAX: float = 3.0
CONTRAST_MIN: float = 0.0
CONTRAST_INCREMENT: float = 0.1
# Blur
BLUR_RADIUS: int = 0
BLUR_RADIUS_MAX: int = 3
BLUR_RADIUS_MIN: int = 0
BLUR_RADIUS_INCREMENT: int = 1
# Threshold
THRESHOLD: int = 2
THRESHOLD_MAX: int = 3
THRESHOLD_MIN: int = 0
THRESHOLD_INCREMENT: int = 1

from os import getcwd

### DEFAULT RECORDING CONSTANTS
MEDIA_OUTPUT_PATH: str = f"{getcwd()}/output"
RECORDING: bool = False

### THERMAL CONTROLLER CONSTANTS
SENSOR_WIDTH: int = 256
SENSOR_HEIGHT: int = 192
DEVICE_FPS: int = 25
DEVICE_NAME: str = "TC001"

### DEFAULT CALCULATED VALUES
TEMPERATURE = 0
TEMPERATURE_RAW = 0
TEMPERATURE_MIN = 0
TEMPERATURE_MAX = 0
TEMPERATURE_AVG = 0
TEMPERATURE_SIG_DIGITS = 2

VIDEO_DEVICE_INDEX: int = 1